language: php

sudo: false

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: hhvm-3.9
      dist: trusty
    - php: nightly

  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer update --no-progress --no-interaction $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
