language: php

sudo: false

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: hhvm
    - php: nightly

  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

